### ISSUE TITLE
Add function parameters

### ISSUE THREAD

**Issue by BonfireScratch** [N-language/PythonN-#1]
Add function parameters

**Comment by BonfireScratch** [comment]
@SimpleBinary could you do it?

**Comment by SimpleBinary** [comment]
I would try, but after reading [Crafting Interpreters](http://www.craftinginterpreters.com), I have realised that GWN was written really badly. I reccomend reading [Crafting Interpreters](http://www.craftinginterpreters.com).

**Comment by BonfireScratch** [comment]
@SimpleBinary The Java and C version of N# are both based on Crafting Interpreters, but the entire thing seems less complicated to me as it is now

**Comment by Dandigit** [comment]
@BonfireScratch You don't need to base N# off of Crafting Interpreters, however you *do* need to rewrite it as a proper programming language implementation - Crafting Interpreters is a great book to teach you how to write these.

@SimpleBinary is right, the GWN codebase that N# is based on is a complete hunk of garbage. Considering that GWN was literally a joke, I think we did OK.

Essentially, your interpreter will have to follow this structure:
- **Lexer**: Takes string of code and returns an array of tokens. (this is the simplest approach, but not the most common)
- **Parser**: Takes array of tokens and returns an Abstract Syntax Tree. This can be done through many *parsing techniques*, however a few of the most common are: Recursive descent, Pratt parsing and LR. You can google "how to write a <parsing technique> parser" to get a good starting point.

From here, the interpreter can either:
- walk the AST through the Visitor pattern and execute actions (very slow)
- or compile the AST down to a more efficient bytecode (faster)

Depending on how complex you're designing N# to be, you may need to implement a semantic analyser to resolve variables or check types.

**Comment by BonfireScratch** [comment]
@SimpleBinary I use Windows

**Comment by BonfireScratch** [comment]
@Dandigit What does Enact use?

**Comment by Dandigit** [comment]
@BonfireScratch Enact's implementation analyses the AST, before compiling it down to bytecode (the faster approach). Also, rather that having the lexer return an array of tokens, Enact's parser asks the lexer for a token when it needs one. (known as lexing on demand)

**Comment by Dandigit** [comment]
@BonfireScratch Also, Enact uses Pratt parsing to parse the tokens.

**Comment by BonfireScratch** [comment]
@Dandigit Could you make a Pratt parser, please? I don't get the whole idea behind it (sorry if it is obviously easy to make but I'm 11)

**Comment by BonfireScratch** [comment]
@Dandigit Actually, what should the parser itself do?

**Comment by Dandigit** [comment]
@BonfireScratch Read above. The parser should either take the list of tokens or request a token from the lexer when it needs one, and create an Abstract Syntax Tree (AST). An AST is a tree of nodes that represent different syntax, e.g. number literals, binary operations and if statements would all have their own types of nodes.

Nodes can reference other nodes, for example a binary operation might add together a number literal and the result of another binary operation. An if statement might reference a variable node. This is where it gets its "tree" nomenclature from.

**Comment by Dandigit** [comment]
@BonfireScratch If you're planning on writing a parser for the first time, I'd go with recursive descent as it's the simplest technique to wrap your head around.

**Comment by BonfireScratch** [comment]
@Dandigit I have managed to make one, (my mathematic evaluator) but thanks anyways!
